<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>MonitorSync</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="../../LICENSE" Link="LICENSE" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="../../licenses/*" Link="licenses/%(Filename)%(Extension)"
             CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <ProjectReference Include="../MonitorSync.Windows/MonitorSync.Windows.csproj" />
    <ProjectReference Include="../MonitorSync.Worker/MonitorSync.Worker.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>
  <Target Name="CopyDevelopmentWorker" AfterTargets="Build">
    <ItemGroup><WorkerFiles Include="../MonitorSync.Worker/bin/$(Configuration)/$(TargetFramework)/MonitorSync.Worker.*" /></ItemGroup>
    <Copy SourceFiles="@(WorkerFiles)" DestinationFolder="$(OutDir)" SkipUnchangedFiles="true" />
  </Target>
</Project>
